// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by temorfeouz/swag at
// 2018-11-15 17:22:04.726797 +0200 EET m=+0.019756117

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/temorfeouz/swag"
)

var doc = `{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/some/update": {
            "post": {
                "description": "MOCK.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "merchant"
                ],
                "summary": "MOCK.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/response.FeeRate"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.CurrencyRate": {
            "type": "object",
            "properties": {
                "limits": {
                    "type": "object",
                    "$ref": "#/definitions/response.Limit"
                },
                "our_fee": {
                    "type": "object",
                    "$ref": "#/definitions/response.FeeRateInfo"
                },
                "ps_fee": {
                    "type": "object",
                    "$ref": "#/definitions/response.FeeRateInfo"
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer"
                        },
                        "exception": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    }
                },
                "result": {
                    "type": "boolean"
                }
            }
        },
        "response.FeeRate": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/response.FeeRateData"
                },
                "result": {
                    "type": "boolean"
                }
            }
        },
        "response.FeeRateData": {
            "type": "object",
            "properties": {
                "deposit": {
                    "type": "object",
                    "$ref": "#/definitions/response.CurrencyRate"
                },
                "withdraw": {
                    "type": "object",
                    "$ref": "#/definitions/response.CurrencyRate"
                }
            }
        },
        "response.FeeRateInfo": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "string"
                },
                "min": {
                    "type": "string"
                },
                "percent": {
                    "type": "string"
                }
            }
        },
        "response.Limit": {
            "type": "object",
            "properties": {
                "check": {
                    "type": "string"
                },
                "max": {
                    "type": "string"
                },
                "min": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
